// Per-page copy for the local-SEO landing template (seo-landing.dc.html?page=<slug>).
const svc = {
  agents: { icon: '◉', title: 'AI voice agents', desc: 'Answer every call 24/7, book appointments, and route the urgent ones to a person.', href: 'nova-ai.dc.html' },
  automation: { icon: '⇄', title: 'Workflow automation', desc: 'Connect the tools you already use so follow-ups, records, and approvals move on their own.', href: 'ai-projects.dc.html' },
  projects: { icon: '◎', title: 'Custom AI projects', desc: 'RAG search, data pipelines, and applications built on your data at a fixed price.', href: 'ai-projects.dc.html' },
  caio: { icon: '↗', title: 'Fractional CAIO', desc: 'Executive AI leadership on a retainer. Strategy, vendors, governance, and a roadmap.', href: 'fractional-caio.dc.html' },
  mvp: { icon: '⌘', title: 'Rapid MVP', desc: 'A working product in eight weeks, usually under $10K. You own the code.', href: 'rapid-mvp.dc.html' },
  connect: { icon: '⊕', title: 'Cellular & internet', desc: 'Business lines, 5G internet, and IoT connectivity reviewed and managed locally.', href: 'tmobile-business.dc.html' },
  vision: { icon: '▤', title: 'Vision & connected systems', desc: 'Cameras, sensors, and operational data surfaced as events your team can act on.', href: 'products.dc.html#vms' }
};
const baseReasons = (loc) => [
  { title: 'We’re actually here', desc: `Indianapolis-based, serving ${loc} in person. Meetings happen across a table, and (317) 508-9493 reaches a person who knows your account.` },
  { title: 'Fixed prices, no lock-in', desc: 'Every proposal has a number on it. Retainers go month to month after 90 days, and you own everything we build.' },
  { title: 'One partner for the whole stack', desc: 'AI, automation, software, and the connectivity underneath. No handoffs between vendors who blame each other.' },
  { title: 'Midwest rates', desc: 'Comparable work bills $200–$400/hour on the coasts. We charge $125–$175, and most projects are fixed-price anyway.' }
];
const baseStats = [
  { n: '500+', label: 'Businesses served', src: 'NevTech client records, 2026' },
  { n: '62%', label: 'of callers hang up when no one answers', src: 'Industry call-handling studies' },
  { n: '40%', label: 'Average telecom cost reduction', src: 'NevTech cellular audits' },
  { n: '5 days', label: 'Typical AI receptionist go-live', src: 'Nova AI deployments' }
];
const baseFaq = (kw, loc) => [
  { q: `How much does ${kw.toLowerCase()} cost?`, a: 'It depends on scope, which is why every engagement starts with a free 15-minute assessment and ends with a fixed-price proposal. Nova AI is priced by call volume; Fractional CAIO retainers start at $1,800/month; Rapid MVPs typically run under $10K.' },
  { q: 'How fast can we start?', a: 'Most first projects begin within two weeks of the assessment. An AI receptionist is live in about five business days; custom AI projects run four to eight weeks.' },
  { q: `Do you work with small businesses in ${loc}?`, a: 'Yes. Most of our clients have between 5 and 200 employees. The first project is sized to pay for itself, not to impress a board.' },
  { q: 'Do I need technical staff?', a: 'No. We handle the technology and train your team in plain language. Human review stays in the loop for anything consequential.' },
  { q: 'What if it doesn’t work?', a: 'We define the measure of success before we start and report on it. If a project isn’t delivering, we say so and adjust or stop. No lock-in after 90 days.' }
];
const page = (o) => ({
  location: o.location || 'Indiana',
  stats: baseStats, reasons: baseReasons(o.location || 'Indiana'), faq: baseFaq(o.keyword, o.location || 'Indiana'),
  callout: { title: 'Start with one workflow', text: 'The businesses that win with AI pick one measurable problem, fix it in weeks, and keep going. We help you choose the right first one.' },
  ...o, services: o.services.map(k => svc[k])
});
export const pages = {
  'ai-indianapolis': page({ keyword: 'AI Indianapolis', location: 'Indianapolis', title: 'AI for Indianapolis businesses,', accent: 'built by people down the road.', subtitle: 'NevTech AI helps Indianapolis companies put AI to work: voice agents that answer every call, automation that removes busywork, and custom AI built on your data.', whatIs: ['Indianapolis businesses aren’t short on AI options. They’re short on partners who show up, fix one problem at a time, and stick around to measure it. That’s the gap NevTech fills.', 'We work with logistics operators on the southwest side, medical practices in Carmel and Fishers, law firms downtown, and trades companies everywhere in between. The problems rhyme: missed calls, repeated data entry, and information nobody can find.'], services: ['agents', 'automation', 'projects', 'caio', 'mvp', 'connect'] }),
  'ai-services-indiana': page({ keyword: 'AI services Indiana', title: 'AI services for Indiana,', accent: 'from strategy to the phone line.', subtitle: 'One partner for AI strategy, custom development, voice agents, automation, and the connectivity underneath. Based in Indianapolis, serving the whole state.', whatIs: ['“AI services” covers a lot: advising on where AI fits, building it, deploying it, and keeping it running. Most vendors do one of those. We do all four, because the handoffs between them are where projects fail.', 'From Fort Wayne to Evansville, we run the same playbook: assess, plan, implement, measure. Fixed prices at every step.'], services: ['caio', 'projects', 'agents', 'automation', 'mvp', 'connect'] }),
  'ai-consulting-indianapolis': page({ keyword: 'AI consulting Indianapolis', location: 'Indianapolis', title: 'AI consulting in Indianapolis', accent: 'that ends in working software.', subtitle: 'Strategy is only useful if someone builds it. Our consultants have each led 25+ implementations and stay through the rollout.', whatIs: ['A good AI consultant tells you what not to do. Which vendor claims to ignore, which process to leave alone, which quick win funds the rest of the roadmap.', 'We start with a free assessment, deliver a 30/60/90-day plan with prices attached, and then build it with you. If you only want the plan, that’s fine too.'], callout: { title: 'Consulting or Fractional CAIO?', text: 'A consultant delivers a project. A Fractional CAIO owns the outcome over time. Many Indianapolis clients start with one and grow into the other.' }, services: ['caio', 'projects', 'automation'] }),
  'ai-consulting-indiana': page({ keyword: 'AI consulting Indiana', title: 'AI consulting for Indiana companies,', accent: 'priced for the Midwest.', subtitle: 'Executive-level AI guidance without coastal rates or a partner layer. Fixed-price roadmaps, fractional leadership, and hands-on delivery.', whatIs: ['Indiana manufacturers, healthcare groups, and logistics firms face the same AI questions as anyone else, with smaller budgets and less patience for theory. Our consulting is built for that: short, specific, and tied to a build.', 'Every engagement produces a written roadmap your team can execute with or without us.'], services: ['caio', 'projects', 'agents', 'automation'] }),
  'ai-automation-indianapolis': page({ keyword: 'AI automation Indianapolis', location: 'Indianapolis', title: 'AI automation in Indianapolis:', accent: 'give busywork a better route.', subtitle: 'Connect your CRM, calendar, inbox, and back office so follow-ups, records, and approvals move without anyone chasing them. Most clients save 20+ hours a week.', whatIs: ['Automation isn’t about replacing people. It’s about removing the re-keying, the “did anyone call them back?”, and the Friday report that takes all of Friday.', 'We map how work actually moves through your Indianapolis business, then automate the handoffs that cost the most time. Human review stays wherever judgment is needed.'], services: ['automation', 'agents', 'projects'] }),
  'ai-automation-indiana': page({ keyword: 'AI automation Indiana', title: 'AI automation across Indiana,', accent: 'one workflow at a time.', subtitle: 'From quote follow-up to invoice matching, we automate the repetitive work that keeps Indiana businesses from growing.', whatIs: ['The best automation projects are boring: they take a task someone does forty times a day and make it happen on its own. Boring pays back fast.', 'We work with businesses statewide, remotely or on site, and start every engagement with the single highest-value workflow.'], services: ['automation', 'agents', 'projects', 'connect'] }),
  'ai-voice-agents-indiana': page({ keyword: 'AI voice agents Indiana', title: 'AI voice agents for Indiana businesses.', accent: 'Every call answered.', subtitle: 'Nova AI answers on the first ring, books appointments, answers questions, and routes emergencies. Live in about five business days.', whatIs: ['An AI voice agent is a receptionist that never sleeps, never puts anyone on hold, and never has a bad day. It knows your services, hours, and rules, and hands off to a person when it should.', 'Indiana trades, practices, and firms use Nova to capture the 62% of callers who would otherwise hang up and call the next name.'], callout: { title: 'Six months free with T-Mobile', text: 'Sign up for T-Mobile for Business through NevTech and Nova’s inbound calling is free for six months.' }, services: ['agents', 'automation', 'connect'] }),
  'ai-agent-development-indiana': page({ keyword: 'AI agent development Indiana', title: 'AI agent development in Indiana,', accent: 'from receptionist to back office.', subtitle: 'Voice agents, chat agents, and internal agents that search, summarize, and act inside your systems. Built on your data with human review where it matters.', whatIs: ['An “agent” is AI that does something, not just says something: books the appointment, files the record, drafts the reply, flags the exception. We build agents that fit inside how your team already works.', 'Every agent ships with clear boundaries, logging, and a person in the loop for consequential actions.'], services: ['agents', 'projects', 'automation', 'caio'] }),
  'custom-ai-development-indiana': page({ keyword: 'Custom AI development Indiana', title: 'Custom AI development for Indiana,', accent: 'scoped and fixed-price.', subtitle: 'RAG search, data pipelines, document AI, and applications built on your data. Four to eight weeks, one outcome, one price.', whatIs: ['Off-the-shelf AI is right when your process looks like everyone else’s. Custom development earns its cost when the process is the business: the dispatch rule, the quoting logic, the ten years of case files.', 'We build in the open with weekly demos and hand over code, documentation, and deployment.'], services: ['projects', 'mvp', 'automation', 'caio'] }),
  'best-ai-companies-indianapolis': page({ keyword: 'Best AI companies Indianapolis', location: 'Indianapolis', title: 'Choosing an AI company in Indianapolis?', accent: 'Ask these questions first.', subtitle: 'Who owns the code. What happens when the model is wrong. How success is measured. Here is how NevTech answers, and what to ask everyone else.', whatIs: ['The best AI company for your business is the one that solves your problem, measures it, and is still reachable a year later. Awards and logos don’t tell you that. Fixed prices, references, and a named person who answers the phone do.', 'NevTech has served 500+ businesses from Indianapolis. We publish our pricing, our process, and our founder’s cell phone.'], callout: { title: 'Five questions for any AI vendor', text: 'Who owns the code? What is the fixed price? How do you handle errors? What will we measure? Who do I call when it breaks?' }, services: ['caio', 'projects', 'agents', 'automation', 'mvp', 'connect'] }),
  'ai-law-firms-indiana': page({ keyword: 'AI for law firms Indiana', title: 'AI for Indiana law firms:', accent: 'intake that qualifies itself.', subtitle: 'AI intake, conflict pre-screening, document search over case files, and follow-up automation. Confidential by design.', whatIs: ['Attorneys lose billable hours to intake calls that don’t fit the practice and to searching for documents they know exist. Both problems are solved.', 'Nova handles intake and scheduling with your screening questions. RAG search puts every brief, filing, and note one question away. Nothing leaves your control.'], services: ['agents', 'projects', 'automation'] }),
  'ai-healthcare-indiana': page({ keyword: 'AI healthcare Indiana', title: 'AI for Indiana healthcare practices,', accent: 'HIPAA-compliant from day one.', subtitle: 'Front-desk AI that books, reminds, and answers insurance questions. Document and data AI for the back office. Signed BAAs, always.', whatIs: ['Medical and dental practices lose patients on hold and staff to scheduling. Nova answers every call under HIPAA-compliant handling, books into your PM system, and cuts no-shows with reminders.', 'Behind the desk, we automate intake, referrals, and records requests so clinical staff do clinical work.'], services: ['agents', 'automation', 'projects', 'connect'] }),
  'ai-manufacturing-indiana': page({ keyword: 'AI manufacturing Indiana', title: 'AI for Indiana manufacturers:', accent: 'know before the line stops.', subtitle: 'Sensor alerts with context, RAG search over maintenance manuals, computer vision for quality, and connectivity for the plant floor.', whatIs: ['Manufacturers run on tribal knowledge and unplanned downtime. AI captures the first and predicts the second.', 'We connect sensors, cameras, and your existing systems so a fault, a defect, or a missing part surfaces as an alert someone can act on.'], services: ['vision', 'projects', 'connect', 'automation'] }),
  'ai-logistics-indiana': page({ keyword: 'AI logistics Indiana', title: 'AI for Indiana logistics:', accent: 'every truck, dock, and document.', subtitle: 'Document AI for BOLs and PODs, IoT fleet tracking, plate recognition at the gate, and automated status updates for customers.', whatIs: ['Indiana moves freight for the country. The paperwork, the status calls, and the yard cameras nobody reviews are where hours disappear.', 'We automate document handling, connect fleets and sensors, and deploy NevTech VMS with LPR so the gate knows who arrived before the driver rolls down the window.'], services: ['vision', 'automation', 'connect', 'projects'] }),
  'ai-home-services-indiana': page({ keyword: 'AI home services Indiana', title: 'AI for Indiana home services:', accent: 'the 7 p.m. call gets booked.', subtitle: 'AI dispatch that answers after hours, quote follow-up that closes, and fleet connectivity that keeps trucks online.', whatIs: ['Plumbers, HVAC, electricians, and roofers lose the most valuable calls of the day to voicemail. Nova answers, triages the emergency, and books the rest for morning.', 'Behind it, automation follows up on every quote and keeps your CRM current without anyone typing.'], services: ['agents', 'automation', 'connect'] }),
  'ai-construction-indiana': page({ keyword: 'AI construction Indiana', title: 'AI for Indiana construction:', accent: 'bids out faster, sites connected.', subtitle: 'AI-assisted takeoffs and proposals, 5G job-site internet, and change-order tracking that survives the text thread.', whatIs: ['Estimating bottlenecks and dead zones on site slow down every Indiana contractor. AI speeds the first; 5G business internet fixes the second.', 'We also automate change orders, daily logs, and subcontractor follow-up so the office stops chasing the field.'], services: ['projects', 'connect', 'automation', 'agents'] })
};
export const order = Object.keys(pages);
